### ISSUE TITLE
Spotify tagging does not work

### ISSUE THREAD

**Issue by Jamlksd** [Marekkon5/onetagger#123]
Spotify tagging does not work after tagging couple a dozen of songs. please fix the problem. thank you.

**Comment by Marekkon5** [comment]
Should be fixed in latest commit, you can get it from Actions tab to try it out. Feel free to comment or reopen if you have any more issues.

**Comment by Jamlksd** [comment]
Unfortunately, there's still a problem with Spotify tagging, usually it take less than 8Min and 250 songs for it to stop.

**Comment by bascurtiz** [comment]
@Jamlksd 
We have tested this with 10.000 tracks in one batch for Auto Tag / Spotify , aswell as Audio Features.
All went good, cause it keeps the rate limit of Spotify in check by now.
In the log it will print:  `[WARN] onetagger_platforms::spotify: Spotify rate limit hit, sleeping for: 1s...`

So I think something else is wrong (some audio file you're trying to process).
Could you share the `onetagger.log` file, by attaching it to your next post here?

In order to find the log file, open One Tagger, click Settings icon > General > Open Data Folder.

**Comment by Jamlksd** [comment]
In order to find the log file, open One Tagger, click Settings icon > General > Open Data Folder.

Could not find the file above neither the does the app open it by itself.

**Comment by bascurtiz** [comment]
@Jamlksd 
Do like this:
https://youtu.be/RMxt0bom63k (windows)
or
https://youtu.be/z9HbNycEbGM (macOS)

**Comment by Jamlksd** [comment]
[onetagger.log](https://github.com/Marekkon5/onetagger/files/9042256/onetagger.log)

**Comment by Jamlksd** [comment]
Thank you both for taking your time to help, appreciate it.

**Comment by bascurtiz** [comment]
@Jamlksd 
From the log file it seems you're not using the latest build from the Actions tab.
We've fixed several issues in between the older version you were using and the latest commit.

Can you try again with the latest build?
See, How to download and install latest build from Actions tab (on macOS): 
https://youtu.be/aRdim2IpVcI

If macOS blocks it follow along from here: 
https://youtu.be/8IDG0igqJQs?t=20

**Comment by Jamlksd** [comment]
I completely deleted the app downloaded the latest version, and the problem got worse?
Doesn't last more than two min, and less than 40 songs.

**Comment by Jamlksd** [comment]
[onetagger.log](https://github.com/Marekkon5/onetagger/files/9049923/onetagger.log)

**Comment by Jamlksd** [comment]
Please note that every other tagger is working, except Spotify.

**Comment by bascurtiz** [comment]
According to your log u have:
- Force Shazam enabled (and therefor totally ignores your metadata artist-title as input and filenames)
- Parse filename enabled (which gets ignored due above)

If I look at your filenames, they look proper enough to use as input.
So I suggest your enable 'parse filename' based on %artist% - %title%

And don't Force shazam. 
Only recommended as last resort due it's higher 'falsely identified rate' compared to tag or filename input.

Hope that helps!

**Comment by Jamlksd** [comment]
Thank you very much, I appreciate your help.
