### ISSUE TITLE
Track number leading zeroes function is not working.

### ISSUE THREAD

**Issue by Salman7236** [Marekkon5/onetagger#188]
I set it to "1" but all tracks are still tagged without any leading zeros. Setting it to any other number also doesn't work.

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit. You can get the build from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thanks

**Comment by Salman7236** [comment]
Thanks for the quick response.  I tried it on two different computers but still not working.

**Comment by Marekkon5** [comment]
Hello, you should use number 1 bigger than zero count (because it's actually the target number width, rather than zero count).

So 1 = 1,2,3,4
2 = 01, 02, 03
3 = 001, 002, 003

Let me know if it works for you.

**Comment by Salman7236** [comment]
Works perfectly. Thanks.
