### ISSUE TITLE
Audio Features tagging should escape "(Origina Mix)"

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/onetagger#3]
Hi, when the title of a track contains (Original Mix) onettager is not able to find it in Spotify. 
This is probably happening because Spotify does not use the (Original Mix) as a description in the titles.

![Screenshot 2021-05-20 164229](https://user-images.githubusercontent.com/74199552/118989213-61e87780-b971-11eb-9a81-752a9fddaa7b.png)

**Comment by bascurtiz** [comment]
Thanks for letting us know @rosgr100 .
1. We've tried to mimick it by finding the track thru the webplayer of Spotify.
2. We've tried to mimick it by finding the track thu the API of Spotify.

Both are unlucky. See if you can replicate.
For API usage go to: https://developer.spotify.com/console/get-search-item/
Fill in Q with `Artist - Title` , Fill in Type with `track`, Click `Get Token` and select some option (doesn't matter which one) & click `Try it`. It will spam the results in bottom-right of the page.

**Webplayer:**
A. https://open.spotify.com/search/3than%20-%20dont%20you%20know
ends up in:
![image](https://user-images.githubusercontent.com/34075088/119034146-56677180-b9ae-11eb-97ee-79bed636f844.png)

B. https://open.spotify.com/search/3than%20-%20don't%20you%20know
ends up in the same results.

C. https://open.spotify.com/search/3than%20-%20don%60t%20you%20know
ends up in:
![image](https://user-images.githubusercontent.com/34075088/119034415-90d10e80-b9ae-11eb-87e9-cffd79411c76.png)
But as you can see, only the remixes.

**API:**
A. https://developer.spotify.com/console/get-search-item/?q=3than%20dont%20you%20know&type=track&market=&limit=&offset=&include_external=
ends up in:
![image](https://user-images.githubusercontent.com/34075088/119034701-eb6a6a80-b9ae-11eb-9938-e1804b9d803a.png)

B. https://developer.spotify.com/console/get-search-item/?q=3than%20don%27t%20you%20know&type=track&market=&limit=&offset=&include_external=
ends up in no result.

C. https://developer.spotify.com/console/get-search-item/?q=3than%20don%27t%20you%20know&type=track&market=&limit=&offset=&include_external=
ends up in:
![image](https://user-images.githubusercontent.com/34075088/119034833-2076bd00-b9af-11eb-9745-3d3402cdc816.png)
Incl. all remixes, and album, but not the track `3than - Don't You Know` itself.

Can you provide more examples?
Because this track in particular looks like trouble on the API side of Spotify.

**Comment by rosgr100** [comment]
I was able to find the track through the desktop app but only as a part of an "album".

![Screenshot 2021-05-21 004725](https://user-images.githubusercontent.com/74199552/119053042-0dff8200-b9b5-11eb-8b01-c95e9bd2f1ca.png)

You will find enough examples in the list bellow.

[ONETAGGER.txt](https://github.com/Marekkon5/onetagger/files/6518931/ONETAGGER.txt)


One more example, although beatport is using the "Original Mix" in the title.

![Screenshot 2021-05-21 005500](https://user-images.githubusercontent.com/74199552/119053963-5c615080-b9b6-11eb-911c-21ea613c9ee2.png)

![Screenshot 2021-05-21 005517](https://user-images.githubusercontent.com/74199552/119053967-5e2b1400-b9b6-11eb-83b2-cb769b87234c.png)

**Comment by Marekkon5** [comment]
Hello, in the latest commit, I've fixed the searching in Spotify, I was able to find the `Pressure - Original Mix` song correctly now.

**Comment by rosgr100** [comment]
Hi , thank you for all the efforts you put in to solving the issues.

So, the issue is solved for tracks with "- original mix" in the title.
But the problem still exist when Spotify, for some reason, doesn't include "original mix" in the title.

![Screenshot 2021-05-24 004748](https://user-images.githubusercontent.com/74199552/119346219-75edeb00-bc89-11eb-87af-112e239a8a59.png)

![Screenshot 2021-05-24 005345](https://user-images.githubusercontent.com/74199552/119346233-7b4b3580-bc89-11eb-83b3-229be54608b5.png)

![Screenshot 2021-05-24 004748](https://user-images.githubusercontent.com/74199552/119346253-81d9ad00-bc89-11eb-9f79-6d765849e525.png)

![Screenshot 2021-05-24 005910](https://user-images.githubusercontent.com/74199552/119346262-83a37080-bc89-11eb-9eda-fe2e16ed14c2.png)


Maybe a solution would be an IF parameter, something like 
IF Artist - Track (Original Mix) fails 
THEN check for Artist - Track

**Comment by Marekkon5** [comment]
Added a patch on master, which cleans up the search query same way as for other platforms. I got match on the tracks you sent. Let me know if it works. Thank you.

**Comment by rosgr100** [comment]
Mostly, it seems to be working now but...
I found another weird behavior by Spotify. There are tracks, which although they are available in Spotify, One Tagger is not able to find them, this is happening because of the dash between artist and the title.

Artist - Title = No match

![Screenshot 2021-05-24 220645](https://user-images.githubusercontent.com/74199552/119397640-f29eba80-bcc5-11eb-9a4d-6af6c60c1a90.png)

Artist Title = Voila

![Screenshot 2021-05-24 220559](https://user-images.githubusercontent.com/74199552/119397674-021e0380-bcc6-11eb-9c70-f7a98316c74f.png)

**Comment by Marekkon5** [comment]
I've implemented a fix, because it is common with search engines, you can try on master.

However I don't think problem in this song is the `-`. 1T uses your first artist in metadata + track title joined with space as query - doesn't add `-` itself, so in this case it doesn't change anything. It's I think the `(Extended Mix)` that's causing the problem.

**Comment by rosgr100** [comment]
Removing the dash didn't do the trick, so you are right, (Extended Mix) is the one to blame.

**Comment by Marekkon5** [comment]
Since extended mixes are slightly different from normal releases I'd consider this more like Spotify doesn't have this track in library rather than 1T problem. Is there any more problems related to this or can this issue be closed?

**Comment by rosgr100** [comment]
I see.
Yes, you can close it, till now i didn't find any other problem regarding this issue.

Once again, thank you for your time! 
😉👏
