### ISSUE TITLE
No album art + No remixer name + No release date 

### ISSUE THREAD

**Issue by tripolarspace** [Marekkon5/onetagger#38]
After the auto tagging gets completed - 

1. There's no album art.  Even after checking the album art tag, setting the resolution to 500 and turning off "Save album to art file".

2. The names of remixers of the track (if any) get removed from the track title.

3. The release date tags are not there as well.

**Comment by Marekkon5** [comment]
Hello, 
1. Album art gets written for me, could you please send names of any specific tracks? Also note if Beatport has no album art (and uses the default grayish-logo art placeholder), it won't be written.
2. Make sure you have `Short title` in advanced options turned off. If yes, some example tracks where it doesn't work would be great.
3. I've just tested it, release date works fine. Which program do you use to check the tags / which audio file format do you use?

Thank you.

**Comment by tripolarspace** [comment]
> Hello,
> 
> 1. Album art gets written for me, could you please send names of any specific tracks that don't? Also note if Beatport has no album art (and uses the default grayish-logo art placeholder), it won't be written.
> 2. Make sure you have `Short title` in advanced options turned off. If yes, some example tracks, where it doesn't work would be great.
> 3. I've just tested it, release date works fine. Which program do you use to check the tags / which audio file format do you use?
> 
> Thank you.

**Comment by tripolarspace** [comment]
Hi, sorry I closed this issue on GitHub by mistake.

**Comment by tripolarspace** [comment]
Thanks

**Comment by tripolarspace** [comment]
1. I have 60 mp3's in a folder, and all of them have an album art on beatport. Anyway here are some names of the tracks from the folder:

- Dhany G, R.Y.A.N. - Antar 
- Stefan Addo - Eunoia (Kenan Savrun Remix)
- Michael A - Trails (Varun Fernandes Remix)

2. Yes I have short title in advanced options turned off. Some examples:

- Tech D - Breath (Fabri Lopez & Andres Moris Remix)
- Tech D - Breath (Jack Lazarus Remix)
- Eddi Shkiper - Message From the Past (DP-6 Remix)
- Husa & Zeyada - Trick of Mind (Oliver Schories Remix)

3. Most of the time I use mp3's. I rarely use WAV / FLAC / AIFF.

**Comment by Marekkon5** [comment]
I've tested all the songs you provided with Title, Release Date, Album Art tags and Overwrite on. All of them got proper album art, the titles were full as original (and I've double checked, yes they were overwritten) and release dates also were there too.

Could you provide log please? (Settings > Open Data Folder > onetagger.log)? Also which program do you use to check the tags? Maybe even providing such processed mp3 would help me debug this. Thank you.

**Comment by Marekkon5** [comment]
You have enabled ID3v2.4, Windows Explorer might not be 100% compatible, maybe try ID3v2.3. I've just checked it in Virtual Machine and I see only "Year", even tho the tag has full release date. Same for album art - I don't see it in Groove/Explorer, but it works in VLC and on my normal system.

So try disabling ID3v2.4 in the advanced settings to use ID3v2.3 to make them show up in Windows Explorer and Groove.

**Comment by tripolarspace** [comment]
Yes, I switched it to ID3v2.3 and it worked. Album Art and release date is tagged now, thank you :)
There's one more small issue, some tracks are getting skipped, even though they have the exact (or almost exact) same name as on beatport. 
These are the tracks that are getting skipped:

- APNITUS - Magic Time (Andres Moris Remix)
- After Burn - How Far Can the Fear Go (Hot TuneiK Remix)
- Lio Q, Anhauser, Nicolas Leonelli - Montevideo
- SEGG, Sasson (FR) - Crossing Path (Original Mix)
- Subandrio, Nishan Lee - Borax (Original Mix)
- Dublew - Nordic Sky (Original Mix)
- Dublew - Nordic Sky (EMPHI Remix)
- Sun Progress - Formation

Hope you can provide a solution for this as well

**Comment by tripolarspace** [comment]
Also, after turning off "short title" all I get is "Original Mix" instead of the remixer names

**Comment by Marekkon5** [comment]
1. Are the tracks skipped or error/no match? I've tried `APNITUS - Magic Time (Andres Moris Remix)` and got succesful match. If they're "skipped" - that means the file might be bad / missing required tag fields. 

2. To the example above - I have short title off and it wrote `Magic Time (Andrés Moris Remix)` to title. Short title means don't write the "version" field (in Beatport it's the small gray text):
![image](https://user-images.githubusercontent.com/15169286/130476050-a21f7f2a-1088-4ba8-a293-a31a6cd5b8cd.png)

**Comment by tripolarspace** [comment]
1. What are the required tag fields ? I'm sure I have the file names right. And the tracks are skipped. There is no failure / error, they are just skipped. I'm sure they're not bad / corrupted.

2. Yes, understood. The track which you tested to tag - Magic Time (Andrés Moris Remix) is getting skipped in mine. And about other remixes, the title is overwritten as "Original Mix" rather than the remixer names.

**Comment by Marekkon5** [comment]
1. You need title and artist tag. If you don't have them, you have to enable the `Parse metadata from filename` option in advanced settings
2. It uses data directly from Beatport. If the remixer is not in the title, it won't be in 1t either.

**Comment by tripolarspace** [comment]
1. I have the title and artist tag in every file. I tried enabling "Parse metadata from filename" as well, still nothing. 
2. The remixer is there in every title, I have checked. 

Also, could you please explain me these following settings:

1. Max Pages
2. Strictness
3. Search Threads

**Comment by Marekkon5** [comment]
1. Uh in that case could you send me sample files? Google Drive / Mega / Dropbox / WeShare anything link is fine

The settings
1. Max pages - how many pages of search results in Beatport to check to find the result
2. The lower the strictness, the less acurate the matches may be. The higher - the less matches you get
3. How many tracks to search for at once. Higher = faster, but more CPU usage (might be bad if you're on old laptop/battery), and also not all platforms support this.

**Comment by tripolarspace** [comment]
Sure, I'll send you on the Drive. Is this the email ? - onetagger@noreply.github.com

**Comment by Marekkon5** [comment]
This is the Github no-reply email, I won't get any messages there. You can send the share link here or on my mail `marekkon50@gmail.com`

**Comment by tripolarspace** [comment]
I've shared 2 folders with you on the drive - "Tracks failed" and "Tracks getting skipped". Please check
Also please try to resolve the remixer name issue. Appreciate your co-operation :)

**Comment by Marekkon5** [comment]
The skipped tracks - they don't have artist tag, and the title tag contains `title - artist`, which is kinda very bad - and even with parse metadata from filenames on it tries to use the title tag as title and therefore getting no results. Those have to be manually editted (or just have tags removed completely and tagged again using `parse metadata from filenames`)

**Comment by Marekkon5** [comment]
And the failed folder - all of them are working
![image](https://user-images.githubusercontent.com/15169286/130488089-61bc1618-1c9f-403d-8726-7dc13ae4eac6.png)

**Comment by Marekkon5** [comment]
By the way - you can also try the unreleased / in progress version - you can get binaries from the Actions tab on Github. Maybe the "failed" tracks will work on there.

**Comment by tripolarspace** [comment]
Got it. I'll get back to you soon after trying this out. Thank you

**Comment by tripolarspace** [comment]
Hey man, I removed the tags completely and turned on "parse metadata from filename". Yet all the 8 tracks are getting skipped

**Comment by tripolarspace** [comment]
Hey, so I removed the tags completely and added the title and artist names in the files, and it worked. Thank you.

**Comment by Marekkon5** [comment]
Great, can I close as solved now?

**Comment by tripolarspace** [comment]
These 4 tracks are just failing man. I don't understand what's the issue. I downloaded them again, removed all the tags, added the title and the artist. But still not happening

![One Tagger 24-08-2021 1 04 03 PM](https://user-images.githubusercontent.com/89389273/130576135-4f5a2ac4-da6e-49e3-bfca-b515d9aa1bdc.png)

**Comment by Marekkon5** [comment]
I've tested some of the songs, I found them. Could you send log + the files again? Thanks

**Comment by tripolarspace** [comment]
Yes, sure -
[onetagger.log](https://github.com/Marekkon5/onetagger/files/7037519/onetagger.log)

**Comment by tripolarspace** [comment]
I've shared the folder "Failed tracks" with you on Google drive, please check

**Comment by Marekkon5** [comment]
All of them are succesful for me. However I told you to try the latest unreleased version, as it has some fixes which improve match rate. According to log, you're using 1.2.1 which is the stable/released one. You can get the latest on Github under the Actions tab.

![image](https://user-images.githubusercontent.com/15169286/130580039-0a2d3de2-4b43-402e-af13-c8e2c5a2dddc.png)

**Comment by tripolarspace** [comment]
Alright, I'm in the actions tab. Which file should I download? Sorry I'm kinda new to GitHub so it's taking me a while to understand all of this

**Comment by Marekkon5** [comment]
Click the newest build (`Use patched rspotify`) and then `onetagger-win-setup` at bottom

**Comment by tripolarspace** [comment]
I downloaded "Use patched spotify", which folder / location should I put it ?

**Comment by Marekkon5** [comment]
You open it and and open the installer inside, same way as regular release.

**Comment by tripolarspace** [comment]
There's no installer inside man. Forgive me but this is just getting more complicated for me. Also do I need to install the dependencies (rustup, node, Visual Studio 2019 Build Tools) as mentioned in the description ?

**Comment by bascurtiz** [comment]
Bro, just do it like this: https://www.youtube.com/watch?v=qLz_X4c9XSM

**Comment by tripolarspace** [comment]
Thanks for this, I already did that bro. Actually I also downloaded the .yml file, and was wondering where to place it lol. Sorry I'm new to GitHub so it's taking me time to process.

So this is all you have to do right ? Whenever there's a new version in the Actions tab, you just download the onetagger setup (exe) file and install it ?

**Comment by Marekkon5** [comment]
yes

**Comment by tripolarspace** [comment]
Worked in the latest version (1.2.2). Thanks a lot for you co-operation @Marekkon5 and @bascurtiz , amazing application.
